language: node_js
node_js:
- '10.15'

script:
  - gulp build --prod

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  committer-from-gh: true
  skip-cleanup: true
  keep-history: true
  local-dir: build
  target-branch: master
  on:
    branch: gh_pages
