language: node_js
node_js:
- '10.15'

script:
  - gulp build --prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local-dir: build
  target-branch: master
  on:
    branch: gh-pages
